# action.yml

# ███╗   ███╗███████╗████████╗████████╗██╗     ███████╗ ██████╗██╗
# ████╗ ████║██╔════╝╚══██╔══╝╚══██╔══╝██║     ██╔════╝██╔════╝██║
# ██╔████╔██║█████╗     ██║      ██║   ██║     █████╗  ██║     ██║
# ██║╚██╔╝██║██╔══╝     ██║      ██║   ██║     ██╔══╝  ██║     ██║
# ██║ ╚═╝ ██║███████╗   ██║      ██║   ███████╗███████╗╚██████╗██║
# ╚═╝     ╚═╝╚══════╝   ╚═╝      ╚═╝   ╚══════╝╚══════╝ ╚═════╝╚═╝
# MettleCI DevOps for DataStage       (C) 2025-2026 Data Migrators
#                _
#  ___ _   _ ___| |_ ___ _ __ ___
# / __| | | / __| __/ _ \ '_ ` _ \
# \__ \ |_| \__ \ ||  __/ | | | | |
# |___/\__, |___/\__\___|_| |_| |_|
#      |___/          _
# __   _____ _ __ ___(_) ___  _ __
# \ \ / / _ \ '__/ __| |/ _ \| '_ \
#  \ V /  __/ |  \__ \ | (_) | | | |
#   \_/ \___|_|  |___/_|\___/|_| |_|

name: 'MCIX System Version'
author: 'Data Migrators Pty Ltd'
description: 'Retrieve details on the MCIX container providing DataStage CI/CD capabilities for IBM Software Hub (Cloud Pak)'
branding:
  icon: 'info'
  color: 'blue'

inputs:
  container-registry:
    description: 'The path of the container registry, eg "ghcr.io"'
    required: false
    default: 'ghcr.io'
  image-name:
    description: 'The namespace and name of the MCIX container image providing this task'
    required: false
    default: 'mettleci/mcix'
  image-tag:
    description: 'The tag of the MCIX container image providing this task'
    required: false
    default: 'latest'

  additional-args:
    description: 'Additional raw arguments to append to the mcix command'
    required: false

outputs:
  return-code:
    description: 'The return code of the command'

runs:
  using: 'composite'
  steps:
    - name: Assemble full image name
      id: image
      shell: bash
      run: |
        echo full_path="${{ inputs.container-registry }}/${{ inputs.image-name }}:${{ inputs.image-tag }}">> $GITHUB_OUTPUT

    - name: Run Entrypoint in Variable Base Image
      shell: bash
      run: |
        # 1. Pull the specified variable image
        docker pull ${{ steps.image.outputs.full_path }}
        
        # 2. Run the image, mounting the entrypoint and passing inputs as env vars
        docker run --rm \
          -v ${{ github.workspace }}:/github/workspace \
          -v ${{ github.action_path }}/entrypoint.sh:/entrypoint.sh \
          -w /github/workspace \
          -e PARAM_ACTION_DETAILS="${{ inputs.action-details }}"" \
          -e PARAM_ADDITIONAL_ARGS="${{ inputs.additional-args }}"" \
          --entrypoint /bin/bash \
          ${{ steps.image.outputs.full_path }} \
          /entrypoint.sh
