# action.yml

# ███╗   ███╗███████╗████████╗████████╗██╗     ███████╗ ██████╗██╗
# ████╗ ████║██╔════╝╚══██╔══╝╚══██╔══╝██║     ██╔════╝██╔════╝██║
# ██╔████╔██║█████╗     ██║      ██║   ██║     █████╗  ██║     ██║
# ██║╚██╔╝██║██╔══╝     ██║      ██║   ██║     ██╔══╝  ██║     ██║
# ██║ ╚═╝ ██║███████╗   ██║      ██║   ███████╗███████╗╚██████╗██║
# ╚═╝     ╚═╝╚══════╝   ╚═╝      ╚═╝   ╚══════╝╚══════╝ ╚═════╝╚═╝
# MettleCI DevOps for DataStage       (C) 2025-2026 Data Migrators
#                _
#  ___ _   _ ___| |_ ___ _ __ ___
# / __| | | / __| __/ _ \ '_ ` _ \
# \__ \ |_| \__ \ ||  __/ | | | | |
# |___/\__, |___/\__\___|_| |_| |_|
#      |___/          _
# __   _____ _ __ ___(_) ___  _ __
# \ \ / / _ \ '__/ __| |/ _ \| '_ \
#  \ V /  __/ |  \__ \ | (_) | | | |
#   \_/ \___|_|  |___/_|\___/|_| |_|

name: 'MCIX System Version'
author: 'Data Migrators Pty Ltd'
description: 'Retrieve details on the MCIX container providing DataStage CI/CD capabilities for IBM Software Hub (Cloud Pak)'
branding:
  icon: 'info'
  color: 'blue'

inputs:
  container-registry:
    description: 'The path of the container registry, eg "icr.io"'
    required: false
    default: ''
  image-name:
    description: 'The namespace and name of the MCIX container image providing this task'
    required: false
    default: ''
  image-tag:
    description: 'The tag of the MCIX container image providing this task'
    required: false
    default: ''
  registry-user:
    description: 'Username for sourcing the image from a private container registry'
    required: false
    default: ''
  registry-api-key:
    description: 'API Key for sourcing the image from a private container registry'
    required: false
    default: ''


  additional-args:
    description: 'Additional raw arguments to append to the mcix command'
    required: false

outputs:
  return-code:
    description: 'The return code of the command'

runs:
  using: 'composite'
  steps:
# Image name prioritises in order (can mix and match between inputs and environment variables)
#   1 - Custom action inputs: 
#       - container-registry 
#       - image-name
#       - image-tag
#   2 - Environment variables:
#       - IMAGE_REGISTRY (default 'icr.io')
#       - IMAGE_NAME (default 'mettleci/mcix')
#       - IMAGE_TAG (default 'latest')
    - name: Assemble full image name
      id: image
      shell: bash
      run: |#!/bin/bash
        REG=""
        IMG=""
        TAG=""

        if [[ "${{ inputs.container-registry }}" != "" ]]; then
          REG="${{ inputs.container-registry }}"
        else 
          REG="${CONTAINER_REGISTRY:-icr.io}"
        fi

        if [[ "${{ inputs.image-name }}" != "" ]]; then
          IMG="${{ inputs.image-name }}"
        else 
          IMG="${IMAGE_NAME:-mettleci/mcix}"
        fi

        if [[ "${{ inputs.image-tag }}" != "" ]]; then
          TAG="${{ inputs.image-tag }}"
        else 
          TAG="${IMAGE_TAG:-latest}"
        fi

        echo "Selected container image: $REG/$IMG:$TAG"

        echo registry="$REG">> $GITHUB_OUTPUT
        echo full_path="$REG/$IMG:$TAG">> $GITHUB_OUTPUT

# Registry credentials prioritise explicit inputs or environment variables. 
# There are no defaults if neither are supplied: the the container registry is assumed to be public,
# so no docker login will be attempted before trying to pull the image.
    - name: Determine private container registry credentials
      id: private_registry
      shell: bash
      run: |#!/bin/bash
        if [[ "${{ inputs.registry-user }}" != "" ]]; then
          echo username="${{ inputs.registry-user }}">> $GITHUB_OUTPUT
          echo apikey="${{ inputs.registry-api-key }}">> $GITHUB_OUTPUT
        else
          echo username="$REGISTRY_USER">> $GITHUB_OUTPUT
          echo apikey="$REGISTRY_API_KEY">> $GITHUB_OUTPUT
        fi

# NOTE: If no image or credentials are specified as either imputs or environment variables,
# this step will attempt to pull the image 'icr.io/mettleci/mcix:latest' without credentials, which is guaranteed to fail authentication.
    - name: Run Entrypoint in Variable Base Image
      shell: bash
      env: 
        REG: ${{ steps.image.outputs.registry }}
        REG_USR: ${{ steps.private_registry.outputs.username }}
        REG_APIKEY: ${{ steps.private_registry.outputs.apikey }}
      run: |#!/bin/bash
        #1. If credentials have been specified, the assumption is that the container registry is private and authentication is required
        if [[ "$REG_USR" != "" && "$REG_APIKEY" != "" ]]; then
          echo "Credentials have been specified. Attempting to log into a private or managed registry."
          echo "$REG_APIKEY" | docker --log-level debug login $REG --username "$REG_USR" --password-stdin
        fi

        # 2. Pull the specified variable image
        docker pull ${{ steps.image.outputs.full_path }}
        
        # 3. Run the image, mounting the entrypoint and passing inputs as env vars
        docker run --rm \
          -v ${{ github.workspace }}:/github/workspace \
          -v ${{ github.action_path }}/entrypoint.sh:/entrypoint.sh \
          -w /github/workspace \
          -e GITHUB_ACTIONS=true \
          -e GITHUB_OUTPUT="$GITHUB_OUTPUT" \
          -v "$GITHUB_OUTPUT:$GITHUB_OUTPUT" \
          -e GITHUB_ENV="$GITHUB_ENV" \
          -v "$GITHUB_ENV:$GITHUB_ENV" \
          -e GITHUB_STEP_SUMMARY=$GITHUB_STEP_SUMMARY \
          -v "$GITHUB_STEP_SUMMARY:$GITHUB_STEP_SUMMARY" \
          -e PARAM_ACTION_DETAILS="${{ inputs.action-details }}" \
          -e PARAM_ADDITIONAL_ARGS="${{ inputs.additional-args }}" \
          --entrypoint /bin/bash \
          ${{ steps.image.outputs.full_path }} \
          /entrypoint.sh

